
apiVersion: v1
kind: PersistentVolume
metadata:
  name: masktv-app-pv
  labels:
    app: masktv-app
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/EFS/app/html-file  # Path on all nodes
