apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: masktv-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1  # Correct API version for Deployment
    kind: Deployment
    name: masktv-app-deployment
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

