apiVersion: apps/v1
kind: Deployment
metadata:
  name: masktv-app-deployment
  labels: 
    app: masktv-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: masktv-app
  template:
    metadata:
      labels:
        app: masktv-app
    spec:
      containers:
        - name: masktv-app-container
          image: masktv/masktv:app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
          volumeMounts:
            - name: masktv-app-pv
              mountPath: /var/www/html 
            - name: app-log-pv
              mountPath: /var/log/apache2
            #- name: app-config-pv
             # mountPath: /etc/apache2
      volumes:
        - name: masktv-app-pv
          persistentVolumeClaim:
            claimName: masktv-app-pvc
        - name: app-log-pv
          persistentVolumeClaim: 
            claimName: app-log-pvc
        #- name: app-config-pv
         # persistentVolumeClaim:
          #  claimName: app-config-pvc
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 2
