apiVersion: v1
kind: PersistentVolume
metadata:
  name: masktv-app-pv
  labels:
    app: masktv-app
spec:
  storageClassName: ""
  capacity:
    storage: 25Gi #.......SET ACCORDING TO APPLICATION SIZE.........
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany    # so can multiple instance read and write data
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /mnt/deployment-efs/app #...... MAKE DIRECTORY IN MNT
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [controlplane]}
