apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masktv-app-pvc
  labels:
    app: masktv-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: ebs-sc
