apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-log-pv
  labels:
    app: masktv-app
spec:
  storageClassName: "" # Use a specific storage class or leave empty for default
  capacity:
    storage: 2Gi  # Set according to application size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Allows multiple Pods to read and write simultaneously
  persistentVolumeReclaimPolicy:  Retain  # Change to Retain for data preservation
  local:
    path: /mnt/EFS/app/log # Ensure this directory exists on the node

