apiVersion: apps/v1
kind: Deployment
metadata:
  name: masktv-app-deployment
  labels: 
    app: masktv-app
spec:
  template:
    metadata:
      labels:
        app: masktv-app
    spec:
      containers:
        - name: masktv-app-container
          image: # Use the image that we build 
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 100m
          volumeMounts:
            - name: masktv-app-pv
              mountPath: /var/www/html   # CHECK ONCE 
          env:
            - name: MYSQL_HOST
              value: "masktv-mysql-service"   # Service name of MySQL service      
            
            #........................................................................................
            need to add port of database container ?
            #........................................................................................
             
             # insert value from secrets.yaml
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_PASSWORD     
                  
            #- name: MYSQL_DATABASE
              #value: "mydatabase"      # these value must be match with value set in MySQL Dockerfile
            #- name: MYSQL_USER
              #value: "root"            # Or your MySQL user
            #- name: MYSQL_PASSWORD
              #value: "rootpassword"    # Or your MySQL password
              
      imagePullSecrets:
        - name: 
        
      volumes:
        - name: masktv-app-pv
          persistentVolumeClaim:
            claimName: masktv-app-pvc
    replicas: 5
    selector:
      matchLabels:
        app: masktv-app
    strategy: 
      type: RollingUpdate
      rollingUpdate: 
        maxSurge: 2
        maxUnavailable: 2
      
