apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: masktv-mysql-hpa
spec: 
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment 
    name: masktv-mysql-deployment
  minReplicas: 5
  maxReplicas: 20
  metrics:
    - type:
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
