apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masktv-mysql-pvc
  labels:
    app: masktv-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: ebs-sc
