apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masktv-mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # Specify the storage class or leave empty for the default
  resources:
    requests:
      storage: 2Gi  # Set according to your database size
  volumeMode: Filesystem
  volumeName: masktv-mysql-pv   # To Schedule this pvc on db pv [masktv-dp-pv] 

