apiVersion: v1
kind: PersistentVolume
metadata:
  name: masktv-db-pv
  labels:
    app: masktv-app
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /mnt/efs-deployment/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [controlplane]}
