apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: masktv-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi #..SET ACCORDING TO DB SIZE
  volumeMode: Filesystem
  volumeName: masktv-db-pv
