apiVersion: v1
kind: Service
metadata:
  name: masktv-mysql-service
spec:
  selector:
    app: masktv-mysql  # Must match the label of the pods in the MySQL Deployment
  ports:
    - protocol: TCP
      port: 3306        # Port on which the service will be exposed
      targetPort: 3306  # Port on which MySQL listens inside the container
  type: ClusterIP      # Default service type, change if external access is needed

