apiVersion: apps/v1
kind: Deployment
metadata:
  name: masktv-mysql-deployment
  labels:
    app: masktv-mysql
spec:    
  template:
    metadata:
      labels:
        app: masktv-mysql
    spec:
      containers:
        - name: masktv-mysql-container
          image: # mysql image that created by us  
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 100m
              
#  if i store application file on s3 then i will have to attach volume to container with path  
#  I have already enter env variable in docker file then will i have to also mention env variable here ??????          
          env:                               # make sure that values are match with docker image values 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_PASSWORD 

                  
            #- name: MYSQL_ROOT_PASSWORD
              #value: myrootpassword
            #- name: MYSQL_DATABASE
              #value: mydatabase
            #- name: MYSQL_USER
              #value: myuser
            #- name: MYSQL_PASSWORD
              #value: mypassword
              
    replicas: 5
    selector:
      matchLabels:
        app: masktv-mysql
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 2

 

