apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: masktv-mysql-hpa
  labels:
    app: masktv-mysql
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: masktv-mysql-statefulset
  minReplicas: 10
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Target CPU utilization percentage
