apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-deployment
  labels:
    app: download
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download
  template:
    metadata:
      labels:
        app: download
    spec:
      initContainers:
        - name: init-download-extract
          image: masktv/masktv:app  
          command:
            - /bin/sh
            - -c
            - |
              aws s3 cp s3://testing-image-html/latest.tar.gz /tmp/
              tar -xzf /tmp/latest.tar.gz -C /tmp/ 
              cp -r /tmp/* /var/www/html/
              rm -rf /tmp/* 
              chown -R www-data:www-data /var/www/html
              chmod -R 755 /var/www/html
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials 
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials  
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: masktv-app-pv
              mountPath: /var/www/html  
      containers:
        - name: download-container
          image: masktv/masktv:app 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: masktv-app-pv
              mountPath: /var/www/html 
      volumes:
        - name: masktv-app-pv
          persistentVolumeClaim:
            claimName: masktv-app-pvc 
