#!/bin/bash

apt-get update -y
apt-get upgrade -y

# Install necessary packages
apt-get install -y nfs-common 

# Allow NFS and necessary port
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 2049/tcp
ufw allow 3306/tcp
ufw allow 10250/tcp 

# Enable and configure ufw
ufw --force enable 

# Create mount directory
mkdir /mnt/deployment-efs

# Define EFS File System ID and mount point
EFS_ID=fs-09040722c4081b081
REGION=ap-south-1

# Get EFS DNS name
EFS_DNS_NAME="${EFS_ID}.efs.${REGION}.amazonaws.com"

# Mount EFS
mount -t nfs ${EFS_DNS_NAME}:/ /mnt/deployment-efs

# Optionally, add entry to /etc/fstab to ensure it's mounted on reboot
echo "${EFS_DNS_NAME}:/ /mnt/deployment-efs nfs defaults,_netdev 0 0" >> /etc/fstab

# Create directory to store Database and Application file
mkdir /mnt/deployment-efs/app
mkdir /mnt/deployment-efs/db

# Mount all filesystems mentioned in /etc/fstab
mount -a
