#!/bin/bash

apt-get update -y
apt-get upgrade -y

# Install necessary packages
apt-get install -y nfs-common 

# Allow NFS and necessary port
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 2049/tcp
ufw allow 3306/tcp
ufw allow 10250/tcp 

# Enable and configure ufw
ufw --force enable 

# .......................Create mount directory..................

mkdir /mnt/EFS


# Create mount directory
REGION=ap-south-1

# .......................EFS DNS name............................

EFS_DNS_NAME="Mention-EFS_ID.efs.${REGION}.amazonaws.com"

# .......................Mount EFS..............................

mount -t nfs ${EFS_DNS_NAME}:/ /mnt/EFS

# ............add entry to /etc/fstab to ensure it's mounted on reboot.......................

echo "${EFS_DNS_NAME}:/ /mnt/EFS nfs defaults,_netdev 0 0" >> /etc/fstab

# ......................Refresh Mount-path......................

mount -a

mkdir /mnt/EFS/app
mkdir /mnt/EFS/db

mkdir /mnt/EFS/app/public_html
mkdir /mnt/EFS/app/log

mkdir /mnt/EFS/db/Log
mkdir /mnt/EFS/db/database
