apiVersion: apps/v1
kind: Deployment
metadata:
  name: masktv-phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: masktv-phpmyadmin-container
          image: phpmyadmin:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "masktv-mysql-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_PASSWORD
