apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
data: 
  MYSQL_ROOT_PASSWORD:  bXlyb290cGFzc3dvcmQ=      # Base64-encoded value of 'myrootpassword'
  MYSQL_DATABASE:  bXlkYXRhYmFzZQ==               # Base64-encoded value of 'mydatabase'
  MYSQL_USER:  bXl1c2Vy                           # Base64-encoded value of 'myuser'
  MYSQL_PASSWORD:  bXlwYXNzd29yZA==               # Base64-encoded value of 'mypassword'
